# Generated by Django 3.2.5 on 2021-07-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('time', models.IntegerField(null=True)),
                ('difficulty', models.FloatField(null=True)),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
    ]
